# General configs
UPLOAD_DIRECTORY: 'uploads/'
ALLOWED_VIDEO_EXTENSIONS : ['mp4', 'MP4']
ALLOWED_JSON_EXTENSIONS : ['json']
ALLOWED_TRANSCRIPT_EXTENSIONS : ['csv', 'xlsx', 'db']
DB_DIRECTORY : 'db/'
TEMP_FILES_FOLDER: 'temp_files'
TRANSCRIPT_DB_PATH: 'transcript.db'

# Speech reco configs
SAMPLE_RATE_HERTZ: 44100
ENABLE_AUTOMATIC_PUNCTUATION: True
ENABLE_WORD_TIME_OFFSETS: True
LANGUAGE_CODE: en-US

# Video Configs
BG_COLOR: white
FONT: Georgia
FONT_COLOR: black
FONT_SIZE: 1
X_POS: center
Y_POS: dynamic
ALIGN: South

# Output configs
CODEC: libx264
AUDIO_CODEC: aac
